import "./helpers/env.js";
import { after, before, describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  createAnalysisTestApp,
  signIn,
  bearer,
  productsWithOlderOwnAnchor,
  type Harness,
  type Json,
} from "./helpers/harness.js";

/**
 * PARITY-01…PARITY-10 — the backend against the validated frontend engine.
 *
 * This is the point of Phase 5. The frontend analytical engine is already
 * validated; moving it to the backend only means anything if the two produce
 * the same answers for the same inputs. So the fixture records what the
 * ENGINE says — generated by `scripts/export-analysis-parity-fixture.mjs`,
 * which runs on the frontend side where those modules are loadable — and
 * every assertion here compares a STRUCTURED value against it.
 *
 * Nothing here compares a rendered sentence. Prose is presentation; the
 * numbers and the finding identities are the analysis.
 *
 * TWO KNOWN GAPS, asserted as exactly two:
 *   · `wtp`    — the hedonic willingness-to-pay model
 *   · `bridge` — maps the three strategy prices into the analysis
 * Both are the pricing recommendation rather than inputs to it. The test
 * below requires the difference to be precisely these and nothing else.
 */

type Fixture = {
  notMigrated: string[];
  caseCount: number;
  cases: Array<Json>;
};

/**
 * Read eagerly, at module scope.
 *
 * `describe` bodies run while the module is evaluating — before any
 * `before` hook — and each product needs its own named test rather than one
 * loop reporting a single pass or fail for all ten. So the fixture has to be
 * available synchronously here.
 */
const FIXTURE_PATH = join(fileURLToPath(new URL(".", import.meta.url)), "fixtures", "analysis-parity.json");
const fixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Fixture;
const loadCases = (): Json[] => fixture.cases;

let h: Harness;
let token: string;

/** Floating point, not approximation: the two sides run the same arithmetic. */
const TOLERANCE = 1e-9;

const closeTo = (actual: unknown, expected: unknown, label: string) => {
  if (expected == null || actual == null) {
    assert.equal(actual ?? null, expected ?? null, label);
    return;
  }
  const a = Number(actual);
  const e = Number(expected);
  assert.ok(
    Math.abs(a - e) <= TOLERANCE,
    `${label}: backend ${a}, engine ${e} (difference ${Math.abs(a - e)}, tolerance ${TOLERANCE})`
  );
};

/**
 * Products the per-product reference date resolves differently from the
 * global one — the only ones where this fixture's global anchoring and the
 * backend's can disagree. Computed from the seeded data, not listed.
 */
let olderAnchor: Set<string> = new Set();

before(async () => {
  h = await createAnalysisTestApp(fixture.cases.map((c) => c.productId as string));
  ({ token } = await signIn(h, "parity@example.com"));
  olderAnchor = await productsWithOlderOwnAnchor(h.db);
});
after(async () => {
  await h.close();
});

const get = async (url: string) => {
  const res = await h.app.inject({ method: "GET", url: `/api/v1${url}`, headers: bearer(token), remoteAddress: "10.70.0.1" });
  return { status: res.statusCode, body: res.json() as Json };
};

/** Every page of the competitor endpoint, so membership can be compared whole. */
async function allCompetitors(productId: string): Promise<Json[]> {
  const out: Json[] = [];
  for (let page = 1; page <= 20; page++) {
    const { body } = await get(`/products/${productId}/competitors?page=${page}&pageSize=100`);
    out.push(...((body["data"] as Json[]) ?? []));
    if (!body["pagination"]?.hasNext) break;
  }
  return out;
}

/** The analysis over the product's WHOLE observed history, as the engine uses. */
async function fullAnalysis(testCase: Json): Promise<Json> {
  const history = testCase.history as Json | null;
  const query = history ? `?from=${history.firstDate}&to=${history.lastDate}` : "";
  const { status, body } = await get(`/products/${testCase.productId}/analysis${query}`);
  assert.equal(status, 200, `analysis for ${testCase.productId}`);
  return body["data"] as Json;
}

/* ================================================== competitive set parity */

describe("PARITY-01/02/03 — the competitive set", () => {
  it("the fixture covers the shapes the engine has to handle", () => {
    assert.equal(fixture.cases.length, 10);
    const levels = new Set(fixture.cases.map((c) => (c.competitiveSet as Json).coverage.level));
    assert.ok(levels.has("strong"), "a strong-coverage product");
    assert.ok(levels.has("insufficient"), "a refusal case");
    assert.ok(
      fixture.cases.some((c) => c.unitBasis != null),
      "a product where per-unit analysis is meaningful"
    );
    assert.ok(
      fixture.cases.some((c) => c.unitBasis == null),
      "a product where per-unit analysis must be suppressed"
    );
    assert.ok(
      fixture.cases.some((c) => (c.marketplaceRows as Json[]).length === 1),
      "a single-marketplace product"
    );
  });

  for (const testCase of loadCases()) {
    it(`PARITY-01 ${testCase.productId}: membership and tiers match the engine`, async () => {
      const expected = testCase.competitiveSet as Json;
      const actual = await allCompetitors(testCase.productId as string);

      // Membership, as a set: the backend may order within a tier by the same
      // rank but a difference in stable-sort tie-breaking is not a difference
      // in analysis.
      assert.deepEqual(
        actual.map((c) => c.productId).sort(),
        [...(expected.memberIds as string[])].sort(),
        `${testCase.productId}: competitive-set membership`
      );

      const tierOf = new Map(actual.map((c) => [c.productId as string, c.tier as string]));
      for (const id of expected.directIds as string[]) {
        assert.equal(tierOf.get(id), "direct", `${testCase.productId}: ${id} should be direct`);
      }
      for (const id of expected.comparableIds as string[]) {
        assert.equal(tierOf.get(id), "comparable", `${testCase.productId}: ${id} should be comparable`);
      }
    });

    it(`PARITY-02/03 ${testCase.productId}: similarity, evidence weight and their components match`, async () => {
      const expected = testCase.competitiveSet as Json;
      const actual = await allCompetitors(testCase.productId as string);
      const byId = new Map(actual.map((c) => [c.productId as string, c]));

      for (const member of expected.members as Json[]) {
        const got = byId.get(member.productId as string);
        assert.ok(got, `${testCase.productId}: ${member.productId} missing from the backend set`);
        const at = `${testCase.productId}/${member.productId}`;

        // The endpoint rounds similarity for transport; compare at that
        // precision rather than pretending to more.
        closeTo(got!.similarity, Math.round((member.similarity as number) * 10000) / 10000, `${at} similarity`);
        closeTo(got!.evidenceWeight, member.evidenceWeight, `${at} evidenceWeight`);
        closeTo(got!.currentPriceMinor, member.currentPriceMinor, `${at} currentPriceMinor`);
        assert.equal(got!.sharedMarketplaces, member.sharedMarketplaces, `${at} sharedMarketplaces`);
        assert.deepEqual([...(got!.marketplaceIds as string[])].sort(), member.marketplaceIds, `${at} marketplaces`);
        assert.equal(got!.rating, member.rating, `${at} rating`);
        assert.equal(got!.reviewCount, member.reviewCount, `${at} reviewCount`);
        assert.equal(got!.isSameFamily, member.isSameFamily, `${at} isSameFamily`);

        // The similarity components, so a matching total cannot hide two
        // compensating errors.
        const breakdown = got!.similarityBreakdown as Json;
        const wanted = member.breakdown as Json;
        closeTo(breakdown.specScore, wanted.specScore, `${at} specScore`);
        closeTo(breakdown.tierScore, wanted.tierScore, `${at} tierScore`);
        closeTo(breakdown.priceScore, wanted.priceScore, `${at} priceScore`);
        closeTo(breakdown.marketplaceScore, wanted.marketplaceScore, `${at} marketplaceScore`);

        closeTo((got!.dataQuality as Json).score, Math.round((member.qualityScore as number) * 1000) / 1000, `${at} quality`);

        const spec = got!.specificationMatch as Json;
        assert.equal(spec.match, member.specMatch, `${at} spec match count`);
        assert.equal(spec.partial, member.specPartial, `${at} spec partial count`);
        assert.equal(spec.differ, member.specDiffer, `${at} spec differ count`);
        assert.equal(spec.missing, member.specMissing, `${at} spec missing count`);
      }
    });
  }
});

/* ============================================================ coverage */

describe("PARITY-08 — coverage and refusal state", () => {
  for (const testCase of loadCases()) {
    it(`${testCase.productId}: coverage matches the engine`, async () => {
      const expected = (testCase.competitiveSet as Json).coverage as Json;
      const { body } = await get(`/products/${testCase.productId}/competitors?pageSize=1`);
      const actual = body["coverage"] as Json;

      assert.equal(actual.directCount, expected.directCount, "directCount");
      assert.equal(actual.comparableCount, expected.comparableCount, "comparableCount");
      assert.equal(actual.totalCount, expected.totalCount, "totalCount");
      closeTo(actual.effectiveComparables, expected.effectiveComparables, "effectiveComparables");
      assert.equal(actual.meetsTarget, expected.meetsTarget, "meetsTarget");
      assert.equal(actual.sufficient, expected.sufficient, "sufficient");
      assert.equal(actual.level, expected.level, "level — the refusal state itself");
    });
  }

  it("a product the engine refuses is refused here too, with no findings invented", async () => {
    const refusals = fixture.cases.filter((c) => (c.competitiveSet as Json).coverage.level === "insufficient");
    assert.ok(refusals.length >= 1, "the fixture must contain a refusal case");

    for (const testCase of refusals) {
      const data = await fullAnalysis(testCase);
      assert.equal((data.coverage as Json).level, "insufficient", `${testCase.productId}`);
      assert.equal((data.coverage as Json).limited, true, `${testCase.productId} should be limited`);
      assert.deepEqual(
        (data.findings as Json[]).map((f) => f.id).sort(),
        testCase.findingIds,
        `${testCase.productId}: a refused product must produce exactly the findings the engine produced`
      );
    }
  });
});

/* ============================================= marketplace and history */

describe("PARITY-04 — marketplace comparison and historical statistics", () => {
  for (const testCase of loadCases()) {
    it(`${testCase.productId}: marketplace rows and comparison match`, async () => {
      const data = await fullAnalysis(testCase);

      const expectedRows = testCase.marketplaceRows as Json[];
      const actualRows = data.marketplaceRows as Json[];
      assert.equal(actualRows.length, expectedRows.length, "marketplace row count");

      const byMarketplace = new Map(actualRows.map((r) => [r.marketplaceId as string, r]));
      for (const row of expectedRows) {
        const got = byMarketplace.get(row.marketplaceId as string);
        assert.ok(got, `${testCase.productId}: ${row.marketplaceId} missing`);
        const at = `${testCase.productId}/${row.marketplaceId}`;
        assert.equal(got!.offerCount, row.offerCount, `${at} offerCount`);
        assert.equal(got!.inStockCount, row.inStockCount, `${at} inStockCount`);
        assert.equal(got!.headlineMinor, row.headlineMinor, `${at} headline`);
        assert.equal(got!.landedMinor, row.landedMinor, `${at} landed`);
        assert.equal(got!.effectiveMinor, row.effectiveMinor, `${at} effective`);
        assert.equal(got!.shippingMinor, row.shippingMinor, `${at} shipping`);
        assert.equal(got!.rating, row.rating, `${at} rating`);
        assert.equal(got!.reviewCount, row.reviewCount, `${at} reviewCount`);
        closeTo(got!.trustRating, row.trustRating, `${at} trustRating`);
        assert.equal(got!.matchConfidence, row.matchConfidence, `${at} matchConfidence`);
        assert.deepEqual(got!.promoCount, row.promoCount, `${at} promotion counts by class`);
        assert.equal(got!.hasUniversalPromo, row.hasUniversalPromo, `${at} hasUniversalPromo`);
      }

      const expectedMp = testCase.marketplace as Json | null;
      const actualMp = data.marketplaceAnalysis as Json | null;
      if (expectedMp == null) {
        assert.equal(actualMp, null, `${testCase.productId}: no marketplace analysis expected`);
      } else {
        assert.ok(actualMp, `${testCase.productId}: marketplace analysis missing`);
        assert.equal(actualMp!.pricedCount, expectedMp.pricedCount, "pricedCount");
        assert.equal(
          (actualMp!.cheapest as Json)?.marketplaceId,
          expectedMp.cheapestMarketplaceId,
          "cheapest marketplace"
        );
        assert.equal((actualMp!.dearest as Json)?.marketplaceId, expectedMp.dearestMarketplaceId, "dearest marketplace");
        assert.equal(actualMp!.spreadMinor, expectedMp.spreadMinor, "spreadMinor");
        closeTo(actualMp!.spreadPct, expectedMp.spreadPct, "spreadPct");
        closeTo(actualMp!.medianEffectiveMinor, expectedMp.medianEffectiveMinor, "medianEffectiveMinor");
        closeTo(actualMp!.priceTrustCorrelation, expectedMp.priceTrustCorrelation, "priceTrustCorrelation");
        assert.equal(actualMp!.cheapestIsAlsoBestTrusted, expectedMp.cheapestIsAlsoBestTrusted, "cheapestIsAlsoBestTrusted");
        assert.equal(actualMp!.shippingReordersRanking, expectedMp.shippingReordersRanking, "shippingReordersRanking");
        assert.equal(actualMp!.platformsWithStockGap, expectedMp.platformsWithStockGap, "platformsWithStockGap");
        closeTo(actualMp!.lowestMatchConfidence, expectedMp.lowestMatchConfidence, "lowestMatchConfidence");
      }
    });

    it(`${testCase.productId}: historical statistics match over the same range`, async () => {
      const data = await fullAnalysis(testCase);
      const expected = testCase.history as Json | null;
      const actual = data.history as Json | null;

      if (expected == null) {
        assert.equal(actual, null, `${testCase.productId}: the engine produced no history, so neither may the backend`);
        return;
      }

      assert.ok(actual, `${testCase.productId}: history missing`);
      assert.equal(actual!.observationCount, expected.observationCount, "observationCount");
      assert.equal(actual!.firstDate, expected.firstDate, "firstDate");
      assert.equal(actual!.lastDate, expected.lastDate, "lastDate");
      assert.equal(actual!.minMinor, expected.minMinor, "minMinor");
      assert.equal(actual!.maxMinor, expected.maxMinor, "maxMinor");
      closeTo(actual!.medianMinor, expected.medianMinor, "medianMinor");
      assert.equal(actual!.currentMinor, expected.currentMinor, "currentMinor");
      assert.equal(actual!.percentile, expected.percentile, "percentile");
      closeTo(actual!.volatility, expected.volatility, "volatility");
      assert.equal(actual!.volatilityBand, expected.volatilityBand, "volatilityBand");
      assert.equal(actual!.promoDays, expected.promoDays, "promoDays");
      closeTo(actual!.trendPct, expected.trendPct, "trendPct");
    });
  }
});

/* ================================================ per-unit and competitors */

describe("PARITY-05 — per-unit calculations", () => {
  for (const testCase of loadCases()) {
    it(`${testCase.productId}: unit basis and per-unit figures match`, async () => {
      const data = await fullAnalysis(testCase);
      const expected = testCase.unitBasis as Json | null;
      const actual = data.unitBasis as Json | null;

      if (expected == null) {
        // Suppression is the assertion: no quantity-bearing attribute means
        // no per-unit analysis, and inventing one is the error this guards.
        assert.equal(actual, null, `${testCase.productId}: per-unit analysis must be suppressed`);
        assert.ok(
          !(data.findings as Json[]).some((f) => f.id === "per_unit_reversal"),
          `${testCase.productId}: a per-unit finding without a unit basis`
        );
        return;
      }

      assert.ok(actual, `${testCase.productId}: unit basis missing`);
      assert.equal(actual!.key, expected.key, "unit key");
      assert.equal(actual!.unit, expected.unit, "unit");
      closeTo(actual!.value, expected.value, "unit value");

      const expectedComp = testCase.competitors as Json | null;
      if (!expectedComp) return;
      const actualComp = data.competitors as Json | null;
      assert.ok(actualComp, `${testCase.productId}: competitor analysis missing`);
      closeTo(actualComp!.ownUnitPriceMinor, expectedComp.ownUnitPriceMinor, "ownUnitPriceMinor");
      assert.deepEqual(
        [...(actualComp!.reversals as Json[])].map((r) => r.id).sort(),
        [...(expectedComp.reversalIds as string[])].sort(),
        `${testCase.productId}: per-unit reversals`
      );
    });
  }
});

describe("PARITY-07 — competitor-level derived figures", () => {
  for (const testCase of loadCases().filter((c) => c.competitors != null)) {
    it(`${testCase.productId}: price gaps, trust and counts match`, async () => {
      const data = await fullAnalysis(testCase);
      const expected = testCase.competitors as Json;
      const actual = data.competitors as Json | null;
      assert.ok(actual, `${testCase.productId}: competitor analysis missing`);

      closeTo(actual!.targetTrustRating, expected.targetTrustRating, "targetTrustRating");
      assert.equal(actual!.cheaperCount, expected.cheaperCount, "cheaperCount");
      assert.equal(actual!.dearerCount, expected.dearerCount, "dearerCount");
      assert.equal(actual!.strongerTrustCount, expected.strongerTrustCount, "strongerTrustCount");

      const byId = new Map((actual!.rows as Json[]).map((r) => [r.id as string, r]));
      for (const row of expected.rows as Json[]) {
        const got = byId.get(row.id as string);
        assert.ok(got, `${testCase.productId}: competitor row ${row.id} missing`);
        const at = `${testCase.productId}/${row.id}`;
        assert.equal(got!.tier, row.tier, `${at} tier`);
        closeTo(got!.priceGapPct, row.priceGapPct, `${at} priceGapPct`);
        closeTo(got!.unitPriceMinor, row.unitPriceMinor, `${at} unitPriceMinor`);
        closeTo(got!.unitGapPct, row.unitGapPct, `${at} unitGapPct`);
        assert.equal(got!.cheaperButDearerPerUnit, row.cheaperButDearerPerUnit, `${at} per-unit reversal`);
        closeTo(got!.trustRating, row.trustRating, `${at} trustRating`);
        closeTo(got!.trustDelta, row.trustDelta, `${at} trustDelta`);
      }
    });
  }
});

/* ================================================== findings and statistics */

describe("PARITY-06/09/10 — finding presence and absence", () => {
  for (const testCase of loadCases()) {
    it(`${testCase.productId}: produces exactly the engine's findings, less the two not migrated`, async () => {
      const data = await fullAnalysis(testCase);
      const actual = (data.findings as Json[]).map((f) => f.id as string).sort();
      const expected = (testCase.findingIds as string[]).filter((id) => !fixture.notMigrated.includes(id)).sort();

      // PARITY-09: nothing invented. PARITY-10: nothing legitimately
      // produced by the engine is missing. Both directions, one assertion.
      assert.deepEqual(actual, expected, `${testCase.productId}: findings`);
    });

    it(`${testCase.productId}: each finding keeps its dimension and direction`, async () => {
      const data = await fullAnalysis(testCase);
      const actual = new Map((data.findings as Json[]).map((f) => [f.id as string, f]));

      for (const finding of testCase.findings as Json[]) {
        if (fixture.notMigrated.includes(finding.id as string)) continue;
        const got = actual.get(finding.id as string);
        assert.ok(got, `${testCase.productId}: ${finding.id} missing`);
        assert.equal(got!.dimension, finding.dimension, `${finding.id} dimension`);
        assert.equal(got!.direction, finding.direction, `${finding.id} direction`);
      }
    });
  }

  it("the difference from the engine is EXACTLY the two recommendation findings", async () => {
    // Not "some findings differ" — precisely wtp and bridge, and nothing
    // else. Anything broader would let a genuine omission hide.
    assert.deepEqual([...fixture.notMigrated].sort(), ["bridge", "wtp"]);

    const missingAcrossAll = new Set<string>();
    for (const testCase of fixture.cases) {
      const data = await fullAnalysis(testCase);
      const actual = new Set((data.findings as Json[]).map((f) => f.id as string));
      for (const id of testCase.findingIds as string[]) if (!actual.has(id)) missingAcrossAll.add(id);
    }
    assert.deepEqual([...missingAcrossAll].sort(), ["wtp"], "only `wtp` is absent; `bridge` is not a finding");
  });
});

describe("PARITY-04b — market statistics the next phase will consume", () => {
  for (const testCase of loadCases().filter((c) => c.ownMarket != null)) {
    it(`${testCase.productId}: own-market and competitive statistics match`, async () => {
      const data = await fullAnalysis(testCase);

      const own = data.ownMarket as Json | null;
      const expectedOwn = testCase.ownMarket as Json;
      assert.ok(own, `${testCase.productId}: own market missing`);
      assert.equal(own!.n, expectedOwn.n, "own market n");
      assert.equal(own!.min, expectedOwn.min, "own market min");
      closeTo(own!.median, expectedOwn.median, "own market median");
      assert.equal(own!.max, expectedOwn.max, "own market max");

      const expectedStats = testCase.competitiveStatistics as Json | null;
      if (expectedStats) {
        const stats = data.competitiveStatistics as Json | null;
        assert.ok(stats, `${testCase.productId}: competitive statistics missing`);
        assert.equal(stats!.n, expectedStats.n, "comp stats n");
        assert.equal(stats!.min, expectedStats.min, "comp stats min");
        closeTo(stats!.median, expectedStats.median, "comp stats median");
        assert.equal(stats!.max, expectedStats.max, "comp stats max");
      }
    });
  }

  for (const testCase of loadCases().filter((c) => c.normalMinor != null)) {
    it(`${testCase.productId}: the 90-day normal and its distortion match`, async () => {
      const data = await fullAnalysis(testCase);

      /**
       * The trailing medians anchor on the reference date, and that date is
       * now resolved PER PRODUCT. The change is deliberate: a single live
       * capture in one product used to move the anchor for all 1,172, and
       * every seeded product was then measured against a window its data ends
       * seven weeks before — the one-month window held zero of 96,149
       * observations.
       *
       * The engine that produced this fixture anchors globally, so for a
       * product captured a day before the dataset maximum the two measure
       * ninety days from different days and the median moves by a few rupees.
       * That is two different windows rather than a tolerance, so the
       * anchor-derived values are compared only where the two anchors agree.
       * `reference-date.test.ts` asserts the new rule directly.
       *
       * Everything else in this test — the distortion state and ratio — is
       * still compared for every product.
       */
      if (!olderAnchor.has(testCase.productId as string)) {
        // A one-day error in the window boundary moves this number, which is
        // why it is asserted rather than left implicit in a finding direction.
        closeTo(data.normalMinor, testCase.normalMinor, "normalMinor");
      }
      assert.equal((data.distortion as Json).state, testCase.distortionState, "distortion state");
      closeTo(
        Math.round(((data.distortion as Json).ratio as number) * 1000) / 1000,
        Math.round((testCase.distortionRatio as number) * 1000) / 1000,
        "distortion ratio"
      );
    });
  }

  for (const testCase of loadCases().filter((c) => c.strength != null)) {
    it(`${testCase.productId}: the strength index inputs match`, async () => {
      const data = await fullAnalysis(testCase);
      const expected = testCase.strength as Json;
      const actual = data.strength as Json;

      assert.equal(actual.targetRating, expected.targetRating, "targetRating");
      assert.equal(actual.targetReviews, expected.targetReviews, "targetReviews");
      closeTo(actual.medianRating, expected.medianRating, "medianRating");
      closeTo(actual.medianReviews, expected.medianReviews, "medianReviews");
      assert.equal((actual.specAdvantages as Json[]).length, expected.specAdvantageCount, "spec advantages");
      assert.equal((actual.specDisadvantages as Json[]).length, expected.specDisadvantageCount, "spec disadvantages");
      // `specTies` is deliberately not compared: buildStrength computes it but
      // does not return it, so the engine has no value to compare against.
    });
  }
});
