import "./helpers/env.js";
import { after, before, describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  createAnalysisTestApp,
  signIn,
  bearer,
  productsWithOlderOwnAnchor,
  type Harness,
  type Json,
} from "./helpers/harness.js";

/**
 * REC-01…10, WTP-01…07 — the backend recommendation against the validated
 * frontend engine.
 *
 * The frontend engine is the baseline until an improvement is explicitly
 * justified, so this compares STRUCTURED values: strategy prices, anchor,
 * floor, ceiling, MRP and break-even bounds, the WTP model's own trust
 * verdict, and the refusal state. Never a rendered sentence.
 *
 * The fixture is generated by `scripts/export-pricing-parity-fixture.mjs`,
 * which runs on the frontend side where the engine's modules are loadable.
 */

type Fixture = { caseCount: number; cases: Json[] };

const FIXTURE_PATH = join(fileURLToPath(new URL(".", import.meta.url)), "fixtures", "pricing-parity.json");
const fixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Fixture;
const cases = () => fixture.cases;

let h: Harness;
let token: string;

/**
 * Products whose own last capture predates the dataset maximum. The reference
 * date is resolved per product, so for these the anchor-derived figures are
 * measured over a different ninety days than this fixture was. See the note
 * in analysis-parity.test.ts and the rule in reference-date.test.ts.
 */
let olderAnchor: Set<string> = new Set();

before(async () => {
  h = await createAnalysisTestApp(cases().map((c) => c.productId as string));
  ({ token } = await signIn(h, "pricing-parity@example.com"));
  olderAnchor = await productsWithOlderOwnAnchor(h.db);
});
after(async () => {
  await h.close();
});

const get = async (url: string) => {
  const res = await h.app.inject({ method: "GET", url: `/api/v1${url}`, headers: bearer(token), remoteAddress: "10.80.0.1" });
  return { status: res.statusCode, body: res.json() as Json };
};

/**
 * One request per product, reused across assertions.
 *
 * Five separate `it` blocks compare different parts of the same
 * recommendation, and fetching it in each of them meant computing every
 * recommendation five times — about fifty for twelve products, and five
 * minutes for a file that now runs in one. The recommendation is a pure
 * function of the database, which nothing here mutates, so memoising it costs
 * no fidelity: the assertions still run against a real HTTP response built by
 * the real service.
 */
const cache = new Map<string, Json>();

const recommendationOf = async (productId: string) => {
  const cached = cache.get(productId);
  if (cached) return cached;
  const { status, body } = await get(`/products/${productId}/recommendation`);
  assert.equal(status, 200, `recommendation for ${productId}: ${JSON.stringify(body).slice(0, 300)}`);
  const data = body["data"] as Json;
  cache.set(productId, data);
  return data;
};

/** Money is integer minor units; these must agree exactly, not approximately. */
const exact = (actual: unknown, expected: unknown, label: string) =>
  assert.equal(actual ?? null, expected ?? null, label);

/** Ratios and scores carry floating error; compare at the published precision. */
const closeTo = (actual: unknown, expected: unknown, label: string, tolerance = 1e-9) => {
  if (expected == null || actual == null) {
    assert.equal(actual ?? null, expected ?? null, label);
    return;
  }
  const a = Number(actual);
  const e = Number(expected);
  assert.ok(Math.abs(a - e) <= tolerance, `${label}: backend ${a}, engine ${e} (difference ${Math.abs(a - e)})`);
};

/* ==================================================== the fixture itself */

describe("the parity fixture exercises what it needs to", () => {
  it("covers recommendation, refusal, trusted models and live break-even floors", () => {
    assert.equal(cases().length, 12);
    const recommended = cases().filter((c) => c.status === "recommended");
    const refused = cases().filter((c) => c.status === "insufficient_evidence");
    assert.ok(recommended.length >= 8, "enough recommended products to be worth comparing");
    assert.ok(refused.length >= 2, "at least two refusal cases");

    assert.ok(cases().some((c) => (c.wtp as Json)?.trusted === true), "a TRUSTED attribute model");
    assert.ok(cases().some((c) => (c.wtp as Json)?.trusted === false), "an UNTRUSTED attribute model");
    assert.ok(
      cases().some((c) => (c.breakEven as Json)?.boundMinor != null),
      "a product where the break-even floor is genuinely computed"
    );
    assert.ok(cases().some((c) => c.ceilingSource === "applicable MRP"), "a product the MRP actually caps");
  });
});

/* ======================================================= REC-01 … REC-10 */

describe("REC — the recommendation matches the frontend engine", () => {
  it("REC-01: the endpoint exists and answers for every golden product", async () => {
    for (const testCase of cases()) {
      const data = await recommendationOf(testCase.productId as string);
      assert.ok(data.status, `${testCase.productId}: no status`);
      assert.ok(["recommended", "insufficient_evidence"].includes(data.status as string));
    }
  });

  for (const testCase of cases()) {
    const id = testCase.productId as string;

    it(`REC-10 ${id}: the refusal state matches`, async () => {
      const data = await recommendationOf(id);
      assert.equal(data.status, testCase.status, `${id}: status`);

      if (testCase.status === "insufficient_evidence") {
        // A refused product must produce NO price, not a hedged one.
        assert.equal(data.recommendation, null, `${id}: a refused product returned a price`);
        assert.deepEqual(data.strategies, [], `${id}: a refused product returned strategies`);
        assert.ok((data.missing as Json[]).length > 0, `${id}: refusal with no stated reason`);
      }
    });

    if (testCase.status !== "recommended") continue;

    it(`REC-03/04/05 ${id}: all three strategy prices match exactly`, async () => {
      const data = await recommendationOf(id);
      const expected = testCase.strategies as Json;
      const byKey = new Map((data.strategies as Json[]).map((s) => [s.key as string, s]));

      for (const key of ["fast_sale", "balanced", "premium"] as const) {
        const want = expected[key] as Json | null;
        const got = byKey.get(key);
        assert.ok(got, `${id}: ${key} missing`);
        exact(got!.priceMinor, want!.priceMinor, `${id}: ${key} price`);
        exact(got!.bindingConstraint ? (got!.bindingConstraint as Json).key : null, want!.bindingConstraintKey, `${id}: ${key} binding constraint`);
      }

      // The ordering invariant the engine enforces by its clamp chain.
      const fast = byKey.get("fast_sale")!.priceMinor as number;
      const balanced = byKey.get("balanced")!.priceMinor as number;
      const premium = byKey.get("premium")!.priceMinor as number;
      assert.ok(fast <= balanced && balanced <= premium, `${id}: strategies out of order ${fast}/${balanced}/${premium}`);
    });

    it(`REC-06/07/08/09 ${id}: anchor, floor, ceiling and MRP match`, async () => {

      const data = await recommendationOf(id);

      // Anchor-derived: see the note above olderAnchor.
      if (!olderAnchor.has(id)) {
        exact((data.anchor as Json).minor, (testCase.anchor as Json).minor, `${id}: anchor`);
      }
      assert.equal((data.anchor as Json).basis, (testCase.anchor as Json).basis, `${id}: anchor basis`);
      exact(data.floorMinor, testCase.floorMinor, `${id}: floor`);
      exact(data.ceilingMinor, testCase.ceilingMinor, `${id}: ceiling`);
      assert.equal(data.ceilingSource, testCase.ceilingSource, `${id}: ceiling source`);
      closeTo((data.constraints as Json).travel, testCase.travel, `${id}: travel`);

      const hard = (data.constraints as Json).hard as Json[];
      const mrp = hard.find((c) => c.key === "mrp_ceiling")!;
      exact(mrp.boundMinor, (testCase.mrp as Json).boundMinor, `${id}: MRP bound`);
      assert.equal(mrp.binding, (testCase.mrp as Json).binding, `${id}: MRP binding`);

      const breakEven = hard.find((c) => c.key === "break_even_floor")!;
      exact(breakEven.boundMinor, (testCase.breakEven as Json).boundMinor, `${id}: break-even bound`);
      assert.equal(breakEven.binding, (testCase.breakEven as Json).binding, `${id}: break-even binding`);
    });

    it(`REC-02 ${id}: the premium ceiling and its suppression match`, async () => {

      const data = await recommendationOf(id);
      const expected = testCase.premiumCeiling as Json | null;
      if (!expected) return;
      const actual = data.premiumCeiling as Json;

      assert.equal(actual.basis, expected.basis, `${id}: premium basis`);
      exact(actual.baseMinor, expected.baseMinor, `${id}: premium base`);
      if (!olderAnchor.has(id)) {
        exact(actual.headroomMinor, expected.headroomMinor, `${id}: premium headroom`);
      }
      exact(actual.capMinor, expected.capMinor, `${id}: premium cap`);
      // The invariant the audit exists to protect: pool Q3 must not create a
      // premium on its own when the product has a market of its own.
      assert.equal(actual.poolQ3Suppressed, expected.poolQ3Suppressed, `${id}: pool Q3 suppression`);
    });

    it(`${id}: market statistics and evidence level match`, async () => {

      const data = await recommendationOf(id);
      const market = data.marketContext as Json;

      if (testCase.ownMarket) {
        const own = market.ownMarket as Json;
        assert.ok(own, `${id}: own market missing`);
        exact(own.n, (testCase.ownMarket as Json).n, `${id}: own n`);
        exact(own.min, (testCase.ownMarket as Json).min, `${id}: own min`);
        closeTo(own.median, (testCase.ownMarket as Json).median, `${id}: own median`);
        exact(own.max, (testCase.ownMarket as Json).max, `${id}: own max`);
      }
      if (testCase.compStats) {
        const stats = (data.competitorContext as Json).statistics as Json;
        exact(stats.n, (testCase.compStats as Json).n, `${id}: comp n`);
        closeTo(stats.median, (testCase.compStats as Json).median, `${id}: comp median`);
      }
      if (!olderAnchor.has(id)) {
        exact(market.normalMinor, testCase.normalMinor, `${id}: 90-day normal`);
      }
      assert.equal((market.distortion as Json).state, testCase.distortionState, `${id}: distortion`);

      const evidence = testCase.evidence as Json;
      const actual = (data as Json).evidence as Json;
      assert.equal(actual.level, evidence.level, `${id}: evidence level`);
      closeTo(actual.score, evidence.score, `${id}: evidence score`);
      assert.equal(actual.coverageCap, evidence.coverageCap, `${id}: coverage cap`);
      assert.equal(actual.cappedByCoverage, evidence.cappedByCoverage, `${id}: capped by coverage`);
      assert.deepEqual(
        (actual.checks as Json[]).filter((c) => c.ok).map((c) => c.key).sort(),
        evidence.okChecks,
        `${id}: which evidence checks passed`
      );
    });
  }
});

/* ======================================================= WTP-01 … WTP-07 */

describe("WTP — the attribute model matches, refusals included", () => {
  for (const testCase of cases()) {
    const id = testCase.productId as string;
    const expected = testCase.wtp as Json | null;
    if (!expected || testCase.status !== "recommended") continue;

    it(`WTP-01/02/03/04/06 ${id}: prediction, sample, fit, trust and features match`, async () => {

      const data = await recommendationOf(id);
      const actual = data.wtp as Json;

      assert.equal(actual.trusted, expected.trusted, `${id}: WTP-04 trust state`);
      exact(actual.n, expected.n, `${id}: WTP-02 sample size`);
      // Fit statistics are published rounded to three places; compare there.
      closeTo(actual.adjR2, expected.adjR2, `${id}: WTP-03 adjusted R²`, 1e-9);
      closeTo(actual.r2, expected.r2, `${id}: R²`, 1e-9);
      exact(actual.predictedMinor, expected.predictedMinor, `${id}: WTP-01 predicted price`);
      assert.deepEqual(
        (actual.features as Json[]).map((f) => f.key).sort(),
        expected.featureKeys,
        `${id}: WTP-06 feature set`
      );
      if (!olderAnchor.has(id)) {
        exact(actual.evidencedPremiumMinor, expected.evidencedPremiumMinor, `${id}: evidenced premium`);
      }
      assert.equal(actual.supported, expected.supported, `${id}: premium supported`);
    });

    it(`WTP-07 ${id}: an untrusted model never moves the price`, async () => {
      const data = await recommendationOf(id);
      const wtp = data.wtp as Json;
      if (wtp.trusted) return;

      // The gate: untrusted means zero premium and no headroom above the
      // product's own market, whatever the model happened to predict.
      exact(wtp.evidencedPremiumMinor, 0, `${id}: an untrusted model claimed a premium`);
      assert.equal(wtp.supported, false, `${id}: an untrusted model was marked supported`);
      exact((data.premiumCeiling as Json).headroomMinor, 0, `${id}: an untrusted model bought headroom`);
      assert.equal(
        (data.model as Json).statisticalComponentState,
        wtp.predictedMinor != null ? "untrusted_fallback" : "unavailable_fallback",
        `${id}: the model state must say it fell back`
      );
    });
  }

  it("WTP-05: a product with too few comparables refuses to model", async () => {
    const thin = cases().find((c) => (c.wtp as Json)?.n != null && ((c.wtp as Json).n as number) < 5);
    if (!thin) {
      // Every recommended product happens to clear the sample floor; assert
      // the refusal path through a product that refuses outright instead.
      const refused = cases().find((c) => c.status === "insufficient_evidence")!;
      const data = await recommendationOf(refused.productId as string);
      assert.equal(data.status, "insufficient_evidence");
      return;
    }
    const data = await recommendationOf(thin.productId as string);
    assert.equal((data.wtp as Json).trusted, false);
    assert.equal((data.wtp as Json).predictedMinor, null, "no prediction below the sample floor");
  });

  it("the model reports its own thresholds, so the gate is inspectable", async () => {
    const recommended = cases().find((c) => c.status === "recommended")!;
    const data = await recommendationOf(recommended.productId as string);
    const threshold = (data.wtp as Json).threshold as Json;
    assert.equal(threshold.minObservations, 5);
    assert.equal(threshold.minAdjustedR2, 0.5);
  });
});

/* ------------------------------------------------------------- versioning */

describe("the recommendation is versioned", () => {
  it("every response carries a model version, and it is not hard-coded at the call site", async () => {
    const data = await recommendationOf(cases()[0]!.productId as string);
    assert.equal((data.model as Json).version, "baseline-v1");
    assert.equal((data.model as Json).statisticalComponent, "hedonic-wtp");

    const { body } = await get(`/products/${cases()[0]!.productId}/recommendation`);
    assert.equal((body["meta"] as Json).modelVersion, "baseline-v1");
  });
});
